/*
  Zentraler Inhaltsbereich. Hier lassen sich später Bildlinks, Scale-Werte,
  Fächer, Clubs, Ausflüge, Termine, Lehrer, Räume, Prüfungsformen,
  Materialien und Infotexte ändern.
*/
window.HOGWARTS_CONTENT = {
  repoAssetBase: 'https://raw.githubusercontent.com/FNK-Author/hogwarts_curriculum/main/',
  assets: {
    titleLogo: { src: 'logo.png', fallback: 'logo.png', scale: 1 },
    timeTurner: { src: 't.png', fallback: 't.png', scale: 0.86 },
    stars: { src: 'stars.png', fallback: 'stars.png' },
    printLogo: { src: 'logo_black.png', fallback: 'logo_black.png', scale: 1 }
  },
  houses: [
    { id: 'gryffindor', name: 'Gryffindor', head: 'Professor Minerva McGonagall', colors: ['#DC6353', '#F2C580'], crest: 'g.png', fallback: 'g.png', imageScale: 1.04, description: 'Gryffindor steht für Mut, Tatkraft und die Bereitschaft, für andere einzustehen.', history: 'Das Haus wurde von Godric Gryffindor gegründet und ist für entschlossene Schülerinnen und Schüler bekannt, die auch in schwierigen Momenten Haltung zeigen.', ghost: 'Fast Kopfloser Nick', founder: 'Godric Gryffindor', commonRoom: 'Gryffindor-Gemeinschaftsraum, Gryffindor-Turm', entrance: 'Der Eingang liegt hinter dem Portrait der Fetten Dame und öffnet sich mit dem aktuellen Passwort.', traits: 'Mutig, loyal, direkt, manchmal waghalsig' },
    { id: 'hufflepuff', name: 'Hufflepuff', head: 'Professor Pomona Sprout', colors: ['#F4B245', '#2b261c'], crest: 'h.png', fallback: 'h.png', imageScale: 1.02, description: 'Hufflepuff steht für Geduld, Fairness und verlässliche Freundschaft.', history: 'Helga Hufflepuff nahm Schülerinnen und Schüler mit ganz verschiedenen Talenten auf und legte Wert auf Fleiß, Gemeinschaft und Hilfsbereitschaft.', ghost: 'Der Fette Mönch', founder: 'Helga Hufflepuff', commonRoom: 'Hufflepuff-Gemeinschaftsraum, Kellerflur nahe den Küchen', entrance: 'Der Zugang verbirgt sich bei den Fässern nahe der Küche und öffnet sich durch den richtigen Klopfrhythmus.', traits: 'Fair, freundlich, ausdauernd, bodenständig' },
    { id: 'ravenclaw', name: 'Ravenclaw', head: 'Professor Filius Flitwick', colors: ['#406BA5', '#b98d55'], crest: 'r.png', fallback: 'r.png', imageScale: 1.03, description: 'Ravenclaw steht für Klugheit, Kreativität und Freude an ungewöhnlichen Lösungen.', history: 'Rowena Ravenclaw gründete das Haus für wache Köpfe, die Wissen, Neugier und Eigenständigkeit schätzen.', ghost: 'Die Graue Dame', founder: 'Rowena Ravenclaw', commonRoom: 'Ravenclaw-Gemeinschaftsraum, Ravenclaw-Turm', entrance: 'Der Eingang öffnet sich nicht mit Passwort, sondern mit der richtigen Antwort auf eine Frage oder ein Rätsel.', traits: 'Klug, neugierig, eigenwillig, ideenreich' },
    { id: 'slytherin', name: 'Slytherin', head: 'Professor Severus Snape', colors: ['#0B6D5D', '#c5c7c4'], crest: 's.png', fallback: 's.png', imageScale: 1.02, description: 'Slytherin steht für Ehrgeiz, Entschlossenheit und strategisches Denken.', history: 'Salazar Slytherin gründete das Haus für Schülerinnen und Schüler mit starkem Willen, großem Zielbewusstsein und Sinn für Einfluss.', ghost: 'Der Blutige Baron', founder: 'Salazar Slytherin', commonRoom: 'Slytherin-Gemeinschaftsraum, Kerker unter dem See', entrance: 'Der Eingang liegt in den Kerkern und öffnet sich mit dem aktuellen Passwort vor einer verborgenen Steinwand.', traits: 'Ehrgeizig, loyal zum eigenen Kreis, clever, zielstrebig' },
  ],
  yearLevels: [
    { value: 1, label: '1. Schuljahrgang' }, { value: 2, label: '2. Schuljahrgang' }, { value: 3, label: '3. Schuljahrgang' }, { value: 4, label: '4. Schuljahrgang' },
    { value: 5, label: '5. Schuljahrgang (ZAG)' }, { value: 6, label: '6. Schuljahrgang (UTZ-Vorbereitung)' }, { value: 7, label: '7. Schuljahrgang (UTZ)' }
  ],
  electiveRules: {
    1: { minimum: 0, text: 'In den ersten beiden Schuljahren steht die Grundausbildung im Vordergrund.' },
    2: { minimum: 0, text: 'In den ersten beiden Schuljahren steht die Grundausbildung im Vordergrund.' },
    3: { minimum: 2, text: 'Ab dem dritten Jahr müssen mindestens zwei Wahlpflichtfächer belegt werden.' },
    4: { minimum: 2, text: 'Mindestens zwei Wahlpflichtfächer bleiben Teil deines Curriculums. Die Schulleitung empfiehlt bestehende Wahlpflichtfächer fortzuführen.' },
    5: { minimum: 3, text: 'Ab dem fünften Jahr müssen mindestens drei Wahlpflichtfächer belegt werden.' },
    6: { minimum: 3, text: 'Für die UTZ-Stufe werden die vertiefenden Fortschrittskurrse, sowie der Apparier-Kurs empfohlen.' },
    7: { minimum: 3, text: 'Im Abschlussjahr zählen mindestens drei spezialisierte Wahlpflichtfächer besonders.' }
  },
  days: [
    { id: 'monday', label: 'Montag' }, { id: 'tuesday', label: 'Dienstag' }, { id: 'wednesday', label: 'Mittwoch' }, { id: 'thursday', label: 'Donnerstag' },
    { id: 'friday', label: 'Freitag' }, { id: 'saturday', label: 'Samstag' }, { id: 'sunday', label: 'Sonntag' }
  ],
  timeSlots: [
    { id: 'breakfast', label: 'Frühstück', time: '07:30-08:10', type: 'meal' },
    { id: 'period1', label: '1. Block', time: '08:30-09:30' }, { id: 'period2', label: '2. Block', time: '09:45-10:45' }, { id: 'period3', label: '3. Block', time: '11:00-12:00' },
    { id: 'lunch', label: 'Mittagessen', time: '12:15-13:00', type: 'meal' },
    { id: 'period4', label: '4. Block', time: '13:30-14:30' }, { id: 'period5', label: '5. Block', time: '14:45-15:45' },
    { id: 'dinner', label: 'Abendessen', time: '16:15-17:00', type: 'meal' },
    { id: 'training1', label: 'Trainingsblock I', time: '17:20-18:20' }, { id: 'training2', label: 'Trainingsblock II', time: '18:35-19:35' },
    { id: 'evening', label: 'Abend', time: '19:50-20:50' }, { id: 'night', label: 'Nacht', time: '22:00-23:00' }
  ],
  mealInfo: {
    breakfast: { name: 'Frühstück', teacher: '', room: 'Große Halle, Erdgeschoss', color: '#F2C580', info: 'Das Frühstück in der Großen Halle ist fest im Stundenplan verankert. Die Hauselfen bereiten es in der Hogwarts-Küche vor. Das Frühstück ist geeignet, um Energie zu sammeln und sich mit der Tagespost zu informieren. Stundenplanänderungen werden am schwarzen Brett vor der großen Halle angepinnt.', materials: [] },
    lunch: { name: 'Mittagessen', teacher: '', room: 'Große Halle, Erdgeschoss', color: '#F2C580', info: 'Beim Mittagessen sammeln sich die Häuser zwischen Unterricht und Nachmittagsblöcken, wobei das Essen noch länger stehen bleibt für Schüler, die erst später hungrig sind. Die Belegschaft und die Professoren bitten nur in dringenden Fällen Anliegen während der Mittagspause vorzutragen.', materials: [] },
    dinner: { name: 'Abendessen', teacher: '', room: 'Große Halle, Erdgeschoss', color: '#F2C580', info: 'Das Abendessen beendet den regulären Unterrichtstag. Neben vielen leichten Kosten, wird es auch immer noch eine warme Mahlzeit geben. Es ist zu erinnern, dass die große Halle wenn möglich nicht für Hausaufgaben und Lernen gedacht ist. Danach beginnen Clubs, Trainings, Nachhilfen und gelegentlich nächtliche Astronomie.', materials: [] }
  },
  formTexts: {
    calm: 'Das Pergament merkt sich deine Auswahl in diesem Browser. Du kannst jederzeit zurückspringen und neu ordnen.',
    conflict: 'Mehrfach belegte Zeitblöcke werden rot markiert. Dafür wäre ein Zeitumkehrer zumindest praktisch.'
  },
  studentSuppliesByYear: {
    '1': ['Grundausstattung: drei schwarze Arbeitsumhänge, schwarzer spitzer Hut, Winterumhang, Zauberstab, Kessel aus Zinn Größe 2, Glas- oder Kristallphiolen, Messingwaage, Teleskop, Federkiele, Tinte, Pergament und Truhe mit Namensschild', 'Unterricht: Drachenhauthandschuhe für Kräuterkunde und Zaubertränke, robuste Schuhe für die Gewächshäuser, Sternkartenmappe, Hausaufgabenheft und einfache Zutatenbox', 'Wohnen in Hogwarts: warme Nachtwäsche, Ersatzsocken, Wäschebeutel, persönliche Pflegeartikel, Nähzeug, Wecker und kleine Vorhängeschlösser für die Truhe', 'Optional: Eule, Katze oder Kröte; Briefpapier; Familienfoto; wetterfester Umhang für den Seeweg; kleine Süßigkeitenreserve für lange Lernabende'],
    '2': ['Grundausstattung: Schuluniform, Winterumhang, Zauberstab, Kessel aus Zinn Größe 2, Glas- oder Kristallphiolen, Messingwaage, Teleskop, Federkiele, Tinte, Pergament und Truhe', 'Unterricht: Drachenhauthandschuhe, zusätzliche Phiolen, Zutatenmesser, Schreibmappe, Ersatzfedern und ein Fachregister für die ersten längeren Essays', 'Wohnen in Hogwarts: warmer Reiseumhang, Pflegeartikel, Nähzeug, Wecker, kleine Laterne für erlaubte Abendwege und Namensetiketten für Bücher', 'Optional: eigener Besen ab dem zweiten Schuljahrgang für Freizeitflug und Quidditch-Bewerbung; Besenpflegeset; Eulenleckerlis; Knieschoner für Flugtraining'],
    '3': ['Grundausstattung: vollständige Schuluniform, Zauberstab, Kessel, Phiolen, Messingwaage, Teleskop, Federkiele, Tinte, Pergament und Truhe', 'Unterricht: Drachenhauthandschuhe, robuste Schuhe für Außenunterricht, Notizbuch für Tierwesenbeobachtung, Schutzbrille und Pflanzenetiketten', 'Wohnen und Wege: Hogsmeade-Einverständniserklärung, wetterfester Reiseumhang, kleine Geldbörse, zusammenklappbarer Einkaufsbeutel und Briefpapier', 'Optional: eigener Besen, warmes Sitzkissen für Quidditchtribünen, Thermoflasche, tragbares Notizbuch für Hogsmeade und zusätzlicher Schal in Hausfarben'],
    '4': ['Grundausstattung: Schuluniform, Winterumhang, Zauberstab, Kessel, Phiolen, Messingwaage, Teleskop, Federkiele, Tinte, Pergament und Truhe', 'Unterricht: Drachenhauthandschuhe, robuste Schuhe, Schutzbrille, Lernkartenbox, wetterfeste Tasche und sauber beschriftete Probenfläschchen', 'Wohnen in Hogwarts: Ersatzumhang, persönliche Pflegeartikel, Wäschebeutel, Fachregister und ein zweites Tintenfass für längere Pergamentabgaben', 'Optional: eigener Besen, zusätzlicher Sportumhang, Ohrstöpsel für Gemeinschaftsräume, kleines Reparaturset für Federn und eine verschließbare Süßigkeitenbox'],
    '5': ['Grundausstattung: vollständige Schuluniform, Zauberstab, Kessel, Phiolen, Messingwaage, Teleskop, Schreibzeug, Pergament und Truhe', 'Prüfungsvorbereitung: ZAG-Lernmappe, Karteikarten, Fachregister, Prüfungsplaner, Ersatzfedern, zweite Tintenflasche und sauberer Satz Laborphiolen', 'Wohnen und Lernen: Ohrstöpsel für Lernphasen, warmer Umhang, robuste Tasche für Bibliotheksbücher und beschriftete Ordner für Wahlpflichtfächer', 'Optional: eigener Besen, persönliches Lernpultbrett, Wecker mit leisem Alarm, Glücksbringer nur ohne Zauberwirkung und ein kleiner Vorrat an beruhigendem Tee'],
    '6': ['Grundausstattung: Schuluniform, Winterumhang, Zauberstab, Kessel, Phiolen, Messingwaage, Teleskop, Schreibzeug, Pergament und Truhe', 'UTZ-Vorbereitung: UTZ-Notizmappe, Fachregister, Apparier-Notizheft, erweiterte Zutatenbox, Schutzbrille und zusätzliche Phiolen für längere Brauversuche', 'Wohnen und Reisen: warmer Reiseumhang, robuste Tasche für Hogsmeade und Exkursionen, persönliche Dokumentenmappe und Geldbörse', 'Optional: eigener Besen, Besenpflegeset, stille Lernkerze ohne offenes Feuer, Notizkarten für Berufsberatung und zweites Paar Drachenhauthandschuhe'],
    '7': ['Grundausstattung: vollständige Schuluniform, Zauberstab, Kessel, Phiolen, Messingwaage, Teleskop, Schreibzeug, Pergament und Truhe', 'Abschlussjahr: UTZ-Prüfungsmappe, Fachregister, Abschlussmappe, Ersatzumhang, saubere Laborphiolen, Quellenmappe und persönlicher Wochenplan', 'Wohnen und Abschied: Reiseunterlagen, verschließbare Erinnerungsbox, robuste Tasche für Bewerbungsunterlagen und Ersatzfederkiele', 'Optional: eigener Besen, feiner Schreibkiel für Bewerbungen, kleiner Fotoapparat für Abschlussmomente, zusätzlicher warmer Umhang und persönliche Bibliotheksnotizen für spätere Ausbildung']
  },
  literatureAuthors: {
    astronomy: 'Professor Aurora Sinistra',
    charms: 'Miranda Goshawk',
    defence: 'Quentin Trimble',
    herbology: 'Phyllida Spore',
    history: 'Bathilda Bagshot',
    potions: { default: 'Arsenius Jigger', '6': 'Libatius Borage', '7': 'Libatius Borage' },
    transfiguration: 'Emeric Switch',
    flying: 'Kennilworthy Whisp',
    'ancient-runes': 'Eadric Thorne',
    arithmancy: 'Bridget Wenlock',
    'care-creatures': { default: 'Newt Scamander', '3': 'Edwardus Lima' },
    divination: 'Cassandra Vablatsky',
    'muggle-studies': 'Wilhelm Wigworthy',
    apparition: 'Wilkie Twycross',
    alchemy: 'Nicolas Flamel',
    'advanced-potions': 'Libatius Borage',
    'advanced-charms': 'Miranda Goshawk',
    'advanced-transfiguration': 'Emeric Switch',
    'advanced-creatures': 'Newt Scamander',
    'advanced-defence': 'Quentin Trimble',
    'advanced-herbology': 'Phyllida Spore',
    'advanced-history': 'Bathilda Bagshot',
    wandmaking: 'Garrick Ollivander',
    'pro-quidditch': 'Kennilworthy Whisp',
    dragonology: 'Charlie Weasley',
    'animagus-study': 'Minerva McGonagall'
  },
  curriculumTopicsBySubject: {
    charms: { title: 'Zaubersprüche in diesem Schuljahrgang', years: {
      '1': ['Entsperrungs-Zauber (Alohomora)', 'Schwebezauber (Wingardium Leviosa)', 'Lichtzauber (Lumos)', 'Lichtlöschzauber (Nox)', 'Reparierzauber (Reparo)', 'Reinigungszauber', 'Sanfter Bewegungszauber', 'Blumen-Heraufbeschwörung'],
      '2': ['Sichtbarkeitszauber (Aparecium)', 'Tür-Verschlusszauber (Colloportus)', 'Schrumpfzauber', 'Vergrößerungszauber', 'Schneidezauber', 'Erstarrungszauber', 'Kitzelzauber', 'Gegenzauber einfacher Art'],
      '3': ['Lumos Maxima', 'Lumos Solem', 'Aufrufezauber (Accio)', 'Wegstoßzauber', 'Wasserabweisender Zauber', 'Baumbewegungszauber', 'Beinklammerfluch nur als Fehlanwendung', 'Kleiner Herausstoßzauber'],
      '4': ['Wasser-Aufrufzauber', 'Aufwärtszauber', 'Vogel-Heraufbeschwörungszauber', 'Vogelangriffszauber nur kontrolliert', 'Enthüllungszauber', 'Stimmverstärkungszauber', 'Schalldämpfungszauber', 'Dämpfungszauber'],
      '5': ['Proteuszauber', 'Verdopplungszauber', 'Markierungszauber', 'Schweigezauber', 'Verschwindezauber', 'Levicorpus nur theoretisch', 'Liberacorpus als Gegenzauber', 'Menschen-Enthüllungszauber'],
      '6': ['Nonverbale Anwendung von Aufrufe-, Reparier- und Schweigezaubern', 'Verdopplungszauber', 'Muggelabwehrzauber', 'Gefahrenwarnzauber', 'Augenbindezauber', 'Verwirrungszauber', 'Heilzauber für kleine Verletzungen', 'Atemwegs-Heilzauber'],
      '7': ['Anhaltender Schutzzauber für Orte', 'Schutzzauber gegen Verhexungen', 'Verstärkter Schutzschild', 'Statuen-Belebungszauber', 'Verbindungszauber', 'Fluchumkehr-Effekt', 'Portschlüssel-Zauber nur theoretisch', 'Verfolgungszauber']
    } },
    defence: { title: 'Schutzzauber, Gegenflüche und Flüche in diesem Schuljahrgang', years: {
      '1': ['Entwaffnungszauber nur als sichere Trockenübung', 'Lichtzauber zur Orientierung', 'Lichtlöschzauber', 'Einfacher Gegenzauber', 'Ganzkörperklammerfluch erkennen', 'Wackelbeinfluch erkennen'],
      '2': ['Kitzelzauber', 'Erstarrungszauber', 'Spinnenabwehrzauber', 'Entwaffnungszauber vertiefen', 'Tanzbein-Fluch erkennen', 'Zahnwachstums-Fluch erkennen', 'Einfache Schutzstellung'],
      '3': ['Schildzauber (Protego)', 'Patronuszauber theoretisch', 'Irrwicht-Abwehrzauber', 'Grifflockerungszauber', 'Schockzauber theoretisch', 'Wiederbelebungszauber theoretisch', 'Hinkepank-Abwehr'],
      '4': ['Schockzauber', 'Wiederbelebungszauber', 'Hinderniszauber', 'Reduktionszauber', 'Explosionszauber nur theoretisch', 'Schildzauber im Übungsduell', 'Grindeloh-Abwehr', 'Unverzeihliche Flüche nur zur Erkennung'],
      '5': ['Schildzauber gegen mehrere Angriffe', 'Schockzauber unter Prüfungsdruck', 'Hinderniszauber vertieft', 'Reduktionszauber kontrolliert', 'Schnittfluch nur als Warnbeispiel', 'Cruciatus-Fluch erkennen', 'Imperius-Abwehr theoretisch', 'Dementorenschutz'],
      '6': ['Nonverbaler Schildzauber', 'Nonverbaler Entwaffnungszauber', 'Menschen-Enthüllungszauber', 'Gefahrenwarnzauber', 'Schutzzauber gegen Verhexungen', 'Schutzzauber vor dunkler Magie theoretisch', 'Gegenfluchanalyse', 'Fluchspuren lesen'],
      '7': ['Todesfluch, Imperius-Fluch und Cruciatus-Fluch ausschließlich rechtlich/theoretisch', 'Anhaltender Schutzzauber für Orte', 'Verstärkter Schutzschild', 'Feindabwehrzauber', 'Fluchumkehr-Effekt', 'Verfolgungszauber', 'Komplexe Duellsimulation', 'Erste Reaktion bei Fluchschäden']
    } },
    transfiguration: { title: 'Verwandlungszauber in diesem Schuljahrgang', years: {
      '1': ['Streichholz zu Nadel', 'Farbwechsel kleiner Gegenstände', 'Formwechsel kleiner Gegenstände', 'Rückführung misslungener Verwandlungen', 'Sichere Zielbild-Übungen'],
      '2': ['Tier-zu-Kelch-Verwandlung', 'Kleine Objektverwandlung mit Bewegung', 'Vergrößerung und Rückführung', 'Schrumpfung und Rückführung', 'Teilverwandlungen erkennen'],
      '3': ['Kleintier-Verwandlung theoretisch', 'Objekt zu Kleintier', 'Teekanne-zu-Schildkröte-Übungen', 'Unvollständige Verwandlungen korrigieren', 'Stabilitätskontrolle'],
      '4': ['Vogel-Verwandlung', 'Hasen-Verwandlung', 'Drachenfigur-Verwandlung theoretisch', 'Erscheinungsbild-Verwandlung', 'Partielle Verwandlung', 'Stabile Objektverwandlung unter Zeitdruck'],
      '5': ['Komplexe Objektverwandlung', 'Verschwindezauber', 'Beschwörungsgrundlagen theoretisch', 'Grenzen menschlicher Verwandlung', 'Fehleranalyse bei Zwischenformen'],
      '6': ['Nonverbale Verwandlung', 'Mehrstufige Verwandlungsfolgen', 'Animagus-Theorie', 'Schwere Fehlverwandlungen rückführen', 'Transspezies-Verwandlung theoretisch'],
      '7': ['Fortgeschrittene Beschwörung', 'Statuen-Belebungszauber theoretisch', 'Hochstabile Verwandlungsfelder', 'Menschliche Verwandlung nur theoretisch', 'Rechtliche Grenzen der Transfiguration']
    } },
    potions: { title: 'Zaubertränke in diesem Schuljahrgang', years: {
      '1': ['Heiltrank gegen Furunkel', 'Einfacher Schlaftrunk', 'Vergesslichkeitstrank stark verdünnt', 'Hustenelixier', 'Mildes Aufmunterungselixier', 'Einfache Gegengifte nach Zutatenfamilie'],
      '2': ['Schrumpf-Trank', 'Abschwelltrank', 'Haarsträubetrank', 'Aufpäppel-Trank', 'Schwell-Lösung nur unter Aufsicht', 'Erkennung verdorbener Zutaten'],
      '3': ['Verwirrungsgebräu', 'Stärkungslösung', 'Wundreinigender Trank', 'Flubberwurmschleim-Bindungen', 'Gegengifte mittlerer Stärke', 'Wolfsbann-Trank nur theoretisch'],
      '4': ['Alterungstrank', 'Friedensgebräu', 'Kiemenkraut-Zubereitung theoretisch', 'Vielsaft-Trank nur theoretisch', 'Trank gegen Erschöpfung', 'Giftige Dämpfe sicher erkennen'],
      '5': ['Trank der lebenden Toten', 'Stärkungstrank vertieft', 'Erweiterte Gegengifte', 'Amortentia nur Analyse', 'Felix Felicis nur Theorie und Ethik', 'Zaubertrank Nr. 440 nur Gefahrenkunde'],
      '6': ['Felix Felicis', 'Amortentia', 'Vielsaft-Trank', 'Wolfsbann-Trank', 'Veritaserum theoretisch', 'Doxyzid', 'Euphorie-Elixier', 'Komplexe Trankketten'],
      '7': ['Veritaserum', 'Alraune-Wiederbelebungstrank', 'Giftanalyse und Gegengifte', 'Regenerationstränke', 'Drachenblut-Elixiere', 'Dickflüssiger goldener Zaubertrank nur theoretisch', 'Meistertränke mit engen Temperaturfenstern']
    } },
    herbology: { title: 'Pflanzen in diesem Schuljahrgang', years: {
      '1': ['Flitterblume', 'Lenkpflaumen', 'Fangzähnige Geranie nur Demonstration', 'Einfache Heilkräuter', 'Drachenmist als Dünger', 'Teufelsschlinge nur theoretisch'],
      '2': ['Alraune-Jungpflanzen', 'Abessinische Schrumpelfeige', 'Alihotsi', 'Flussgras', 'Chinesischer Kaukohl', 'Venemosa Tentacula nur aus sicherer Entfernung'],
      '3': ['Kartoffelbauchpilz', 'Mimbulus Mimbeltonia', 'Schlafbohne', 'Giftige Tentakeln erkennen', 'Pflanzenschutzkleidung', 'Pflanzensekrete sicher sammeln'],
      '4': ['Springende Knollen', 'Zitternder Ginsterbusch', 'Kiemenkraut', 'Spulenwurzel', 'Plangentinie', 'Heilpflanzen richtig ernten'],
      '5': ['Kreischbeißer', 'Blutblasenschote', 'Venemosa Tentacula Pflegeprotokoll', 'Reife Alraunen', 'Seltene Heilpflanzen', 'Pflanzengifte und Gegengifte'],
      '6': ['Schlafbohne für Trank der lebenden Toten', 'Mimbulus-Mimbeltonia-Schutzsekret', 'Mondscheinernte', 'Gefährliche Gewächshausroutinen', 'Pflanzenkreuzungen theoretisch'],
      '7': ['Teufelsschlinge-Abwehr vertieft', 'Venemosa Tentacula fortgeschritten', 'Seltene magische Gewächse', 'Pflanzen in Fluchheilung', 'Komplette Gewächshaus-Sicherheitsprüfung']
    } },
    'care-creatures': { title: 'Tierwesen in diesem Schuljahrgang', years: {
      '3': ['Flubberwurm', 'Knarle', 'Feen', 'Porlock', 'Salamander', 'Niffler', 'Baumwächter', 'Hippogreif mit Sicherheitsabstand'],
      '4': ['Einhorn', 'Grindeloh', 'Murtlap', 'Doxy', 'Crup', 'Billywig', 'Feuerkrabbe', 'Knallrümpfiger Kröter nur mit Schutzabstand'],
      '5': ['Thestral', 'Niffler vertieft', 'Baumwächter-Pflege', 'Augurey', 'Kappa', 'Rotkappe', 'Mondkalb', 'Drachenarten nur theoretisch'],
      '6': ['Drachenarten theoretisch', 'Acromantula nur Fallstudie', 'Basilisk nur Warnkunde', 'Demiguise', 'Diricawl', 'Occamy', 'Pogrebin', 'Runespoor'],
      '7': ['Mantikor theoretisch', 'Chimära theoretisch', 'Nundu nur Gefahrenanalyse', 'Quintaped', 'Werwolf rechtlich/medizinisch', 'Phönix', 'Qilin', 'Komplette Gefahrenklassifikation']
    } },
    'advanced-charms': { title: 'Fortgeschrittene Zaubersprüche in diesem Schuljahrgang', years: {
      '5': ['Proteuszauber', 'Schweigezauber', 'Verdopplungszauber', 'Markierungszauber', 'Menschen-Enthüllungszauber', 'Spezial-Enthüllungszauber', 'Gegenzauber zu leichteren Verhexungen', 'Kontrollierte Zauberserien'],
      '6': ['Nonverbale Zauberketten', 'Verwirrungszauber', 'Heilzauber für kleine Verletzungen', 'Atemwegs-Heilzauber', 'Schalldämpfungszauber', 'Muggelabwehrzauber', 'Gefahrenwarnzauber', 'Augenbindezauber'],
      '7': ['Anhaltender Schutzzauber für Orte', 'Schutzzauber gegen Verhexungen', 'Verstärkter Schutzschild', 'Statuen-Belebungszauber', 'Portschlüssel-Zauber nur theoretisch', 'Fluchumkehr-Effekt', 'Spuren-Enthüllungszauber', 'Komplexer Verbindungszauber']
    } },
    'advanced-defence': { title: 'Fortgeschrittene Abwehr, Flüche und Gegenflüche', years: {
      '5': ['Schildzauber gegen Mehrfachangriff', 'Schockzauber', 'Wiederbelebungszauber', 'Hinderniszauber', 'Reduktionszauber kontrolliert', 'Dementorenschutz', 'Imperius-Abwehr nur theoretisch', 'Fluchrecht und Verantwortlichkeit'],
      '6': ['Nonverbaler Schildzauber', 'Nonverbaler Entwaffnungszauber', 'Schutzzauber vor dunkler Magie nur theoretisch', 'Gefahrenwarnzauber', 'Schutzzauber gegen Verhexungen', 'Fluchspuren lesen', 'Schnittfluch-Warnanalyse', 'Dunkle Artefakte erkennen'],
      '7': ['Unverzeihliche Flüche rein theoretisch', 'Fluchumkehr-Effekt', 'Anhaltender Schutzzauber für Orte', 'Feindabwehrzauber', 'Verstärkter Schutzschild', 'Komplexe Duelle', 'Notfall-Gegenflüche', 'Auroren-Fallstudien']
    } },
    'advanced-potions': { title: 'Fortgeschrittene Zaubertränke in diesem Schuljahrgang', years: {
      '5': ['Trank der lebenden Toten', 'Friedensgebräu', 'Amortentia nur Analyse', 'Stärkungslösung', 'Erweiterte Gegengifte', 'Doxyzid', 'Schrumpf- und Anschwelltränke im Vergleich'],
      '6': ['Felix Felicis', 'Amortentia', 'Vielsaft-Trank', 'Wolfsbann-Trank', 'Veritaserum nur theoretisch', 'Euphorie-Elixier', 'Alterungstrank', 'Komplexe Temperaturführung'],
      '7': ['Veritaserum unter strengster Aufsicht', 'Alraune-Wiederbelebungstrank', 'Gifte und Gegengifte', 'Regenerationstränke', 'Drachenblut-Elixiere', 'Dickflüssiger goldener Zaubertrank nur theoretisch', 'Meistertränke', 'Freies Forschungsgebräu unter Aufsicht']
    } },
    'advanced-herbology': { title: 'Fortgeschrittene Pflanzen in diesem Schuljahrgang', years: {
      '5': ['Kreischbeißer', 'Reife Alraunen', 'Venemosa Tentacula nur unter Glas', 'Blutblasenschote', 'Schlafbohne', 'Giftpflanzenprotokolle', 'Kiemenkraut-Pflege', 'Heilpflanzen für ZAG-Gegengifte'],
      '6': ['Mimbulus Mimbeltonia', 'Mondscheinernte der Plangentinie', 'Spulenwurzel', 'Springende Knollen', 'Pflanzenkreuzungen nur theoretisch', 'Heilpflanzen für UTZ-Tränke', 'Teufelsschlinge-Sicherheitsroutinen'],
      '7': ['Seltene magische Gewächse', 'Teufelsschlinge vertieft', 'Venemosa Tentacula fortgeschritten', 'Pflanzengifte und Gegengifte', 'Gewächshaus-Notfallroutinen', 'Prüfungsprojekt Pflegezyklus', 'Schutz magischer Biotope']
    } },
    'advanced-creatures': { title: 'Fortgeschrittene Tierwesen in diesem Schuljahrgang', years: {
      '5': ['Thestral', 'Hippogreif vertieft', 'Niffler-Pflege', 'Baumwächter-Schutz', 'Feuerkrabbe', 'Kappa', 'Rotkappe', 'Mondkalb'],
      '6': ['Drachenarten theoretisch', 'Acromantula nur Fallstudie', 'Basilisk nur Warnkunde', 'Demiguise', 'Occamy', 'Runespoor', 'Pogrebin', 'Werwolf-Ethik'],
      '7': ['Mantikor theoretisch', 'Chimära theoretisch', 'Nundu nur Gefahrenanalyse', 'Quintaped', 'Phönix', 'Qilin', 'Internationale Gefahrenklassifikation', 'Schutzgebiet-Protokolle']
    } },
    dragonology: { title: 'Drachen und Hochrisiko-Tierwesen in diesem Schuljahrgang', years: {
      '5': ['Walisischer Grünling', 'Schwedischer Kurzschnäuzler', 'Chinesischer Feuerball', 'Ungarischer Hornschwanz nur Sicherheitsanalyse', 'Drachenei-Schutzrecht', 'Hitzeschutz und Beobachtungsabstand'],
      '6': ['Norwegischer Stachelbuckel', 'Peruanischer Viperzahn', 'Rumänischer Langhorn', 'Hebridenschwarzdrache', 'Reservatsarbeit und Schutzabstände', 'Erste Hilfe bei Feuerverletzungen'],
      '7': ['Drachenkrankheiten', 'Drachenblut-Anwendungen', 'Drachenberuhigung nur theoretisch', 'Internationale Drachenabkommen', 'Notfall-Portschlüssel-Protokolle', 'Hochrisiko-Arten nur aus Distanz']
    } },
    'advanced-transfiguration': { title: 'Fortgeschrittene Verwandlungszauber in diesem Schuljahrgang', years: {
      '5': ['Verschwindezauber', 'Heraufbeschwörungs-Grundlagen', 'Komplexe Objektverwandlung', 'Rückverwandlungszauber', 'Partielle Verwandlung', 'Animagus-Theorie ohne Selbstversuch'],
      '6': ['Nonverbale Verwandlung', 'Transspezies-Verwandlung nur theoretisch', 'Mehrstufige Verwandlungsfolgen', 'Stabilitätsmessung', 'Fehlverwandlungsanalyse', 'Grenzen lebender Verwandlung'],
      '7': ['Fortgeschrittene Heraufbeschwörung', 'Statuen-Belebungszauber nur theoretisch', 'Hochstabile Verwandlungsfelder', 'Menschliche Verwandlung nur theoretisch', 'Verwandlungsrecht', 'Rückverwandlung nach Fehlzaubern']
    } },
    'animagus-study': { title: 'Animagus-Theorie in diesem Schuljahrgang', years: {
      '5': ['Animagus-Grundformel nur theoretisch', 'Registrierungspflicht', 'Selbstbild und Tiergestalt', 'Risiken unvollständiger Verwandlung', 'Historische Beispiele aus Hogwarts'],
      '6': ['Alraunenblatt-Ritual nur theoretisch', 'Animagus-Trankbestandteile', 'Gewitterbedingung', 'Historische Animagi und Rechtsfälle', 'Abgrenzung zu Verwandlungszaubern'],
      '7': ['Langzeitfolgen freiwilliger Verwandlung', 'Geheimhaltung und Ministeriumsrecht', 'Ethik der Tarnung', 'Fortgeschrittene Fallstudien', 'Warum heimliche Selbstversuche verboten sind']
    } },
    apparition: { title: 'Apparierformeln und Sicherheitsinhalte', years: {
      '6': ['Ziel, Wille und Ruhe', 'Apparieren', 'Disapparieren', 'Zersplintern vermeiden', 'Zielkreis-Prüfung', 'Notfall-Rückkehr', 'Rechtliche Mindestanforderungen'],
      '7': ['Präzisionsapparieren', 'Seit-an-Seit-Apparieren nur theoretisch', 'Anti-Apparier-Schutz erkennen', 'Rechtliche Grenzen des Apparierens', 'Reiseprotokoll', 'Sicheres Ankommen in unbekannten Orten']
    } },
    alchemy: { title: 'Alchemistische Stoffe und Verfahren', years: {
      '6': ['Alchemistische Symbole', 'Metallentsprechungen', 'Reagenzienketten', 'Einfache Transmutation nur theoretisch', 'Stein der Weisen als historische Fallstudie', 'Sicherheitskreise für Laborarbeit'],
      '7': ['Substanzwandel', 'Lebenselixier nur theoretisch', 'Gold-Transmutation nur theoretisch', 'Seltene Katalysatoren', 'Alchemistische Sicherheitskreise', 'Grenzen verantwortlicher Stoffwandlung']
    } },
    wandmaking: { title: 'Zauberstabkunde in diesem Schuljahrgang', years: {
      '5': ['Stechpalme, Eibe, Weide und Esche', 'Phönixfeder', 'Einhornhaar', 'Drachenherzfaser', 'Zauberstab-Bindung', 'Grundlagen der Holztemperamente'],
      '6': ['Resonanzprüfung', 'Bruderstäbe', 'Kernkonflikte', 'Holztemperament', 'Reparaturgrenzen', 'Sichere Arbeit mit Kernmustern'],
      '7': ['Meisterfragen der Zauberstabkunde', 'Fluchumkehr-Effekt durch Bruderstäbe', 'Zauberstabloyalität', 'Gefährliche Kerne nur theoretisch', 'Dokumentationsprotokoll', 'Ethik der Zauberstabwahl']
    } },
    'pro-quidditch': { title: 'Quidditch-Techniken und Spielkunde', years: {
      '5': ['Sucherdrills', 'Jäger-Passfolgen', 'Treiber-Sicherheitswinkel', 'Hüter-Reaktionsübungen', 'Foulkunde', 'Fairplay und Mannschaftsrolle'],
      '6': ['Positionsspiel', 'Spielanalyse', 'Klatscher-Laufwege', 'Wettertaktik', 'Mannschaftskommunikation', 'Belastungssteuerung'],
      '7': ['Profi-Scouting', 'Finaltaktiken', 'Schiedsrichterzeichen', 'Turniervorbereitung', 'Konditionsprüfung', 'Bewerbungsmappe für Vereine']
    } }
  },
  subjects: [
    { id: 'astronomy', name: 'Astronomie', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Aurora Sinistra', room: 'Astronomieturm, oberste Plattform', icon: '', iconScale: 0.86, color: '#4465A6', examForm: 'Sternkartenabgabe, praktische Teleskopprüfung und theoretische Halbjahresprüfung.', materials: ['Sternkarte', 'Teleskop wird im Astronomieturm gestellt', 'Warmer Umhang für Nachtstunden'], literatureByYear: { '1': 'Sterne über Hogwarts - ein Einführungsband in die Astronomie', '2': 'Mondphasen und magische Nächte', '3': 'Sternkarten für Fortgeschrittene', '4': 'Kometen, Konjunktionen und Omen', '5': 'ZAG-Astronomie: Prüfungsatlas', '6': 'UTZ-Himmelskunde I', '7': 'UTZ-Himmelskunde II' }, info: 'Astronomie verbindet Sternkarten, Mondphasen und die Beobachtung magischer Himmelsereignisse. Geprüft wird mit praktischer Teleskoparbeit, Sternbildbestimmung und einer schriftlichen Auswertung nächtlicher Beobachtungen.', sessions: [{ day: 'wednesday', slot: 'night' }] },
    { id: 'charms', name: 'Zauberkunst', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Filius Flitwick', room: 'Klassenzimmer 2E, zweiter Stock, Ostflügel von Hogwarts', icon: '', iconScale: 0.9, color: '#F2C580', examForm: 'Praktische Zaubervorführung, mehrere Pergamentabgaben und kurze Theorieprüfung.', materials: ['Übungsobjekte', 'Federkiel und Pergament'], literatureByYear: { '1': 'Standardzauber, Band 1', '2': 'Standardzauber, Band 2', '3': 'Standardzauber, Band 3', '4': 'Außergewöhnliche Zauberkunst, Band 1', '5': 'Außergewöhnliche Zauberkunst, Band 2', '6': 'Außergewöhnliche Zauberkunst, Band 3', '7': 'Außergewöhnliche Zauberkunst, Band 4' }, info: 'In Zauberkunst werden präzise Zauberstabbewegungen, Aussprache und nützliche Alltagszauber trainiert. Prüfungen bestehen aus einer kurzen Theoriefrage und einer praktischen Vorführung mehrerer Zauber unter Aufsicht.', sessions: [{ day: 'tuesday', slot: 'period3' }, { day: 'thursday', slot: 'period1' }, { day: 'friday', slot: 'period3', yearLevels: [3,4,5,6,7] }] },
    { id: 'defence', name: 'Verteidigung gegen die dunklen Künste', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Severus Snape', room: 'Verteidigungsklassenzimmer, dritter Stock, Nordflügel von Hogwarts', icon: '', iconScale: 0.9, color: '#9b3338', examForm: 'Praktische Verteidigungsprüfung, mündliche Fallanalyse und theoretische Abschlussklausur.', materials: ['Schutzumhang', 'Schutzbrille', 'Schutzhandschuhe', 'Notizpergament und Schreibzeug'], literatureByYear: { '1': 'Dunkle Kräfte: Ein Leitfaden zum Selbstschutz I', '2': 'Verhexungen erkennen II', '3': 'Gegenflüche und Schutzzauber III', '4': 'Dunkle Kreaturen und Abwehr IV', '5': 'ZAG-Verteidigung V', '6': 'UTZ-Verteidigung VI', '7': 'Meisterkurs Defensive Magie VII' }, info: 'Verteidigung gegen die dunklen Künste behandelt Schutzzauber, Flüche, Gegenflüche und die Einschätzung magischer Gefahren. Die Prüfung kombiniert Fallanalyse, Duellhaltung und das saubere Ausführen defensiver Zauber.', sessions: [{ day: 'monday', slot: 'period2' }, { day: 'wednesday', slot: 'period1', yearLevels: [3,4,5,6,7] }, { day: 'friday', slot: 'period2' }] },
    { id: 'herbology', name: 'Kräuterkunde', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Pomona Sprout', room: 'Gewächshaus Unterrichtsgarten', icon: '', iconScale: 0.88, color: '#80BFAD', examForm: 'Praktische Pflanzenpflege, Pflanzensteckbrief und mündliche Sicherheitsabfrage.', materials: ['Drachenhauthandschuhe', 'Ohrenschützer', 'Pflanzenschere'], literatureByYear: { '1': 'Tausend magische Kräuter und Pilze I', '2': 'Gewächshauskunde II', '3': 'Gefährliche Sprösslinge III', '4': 'Heilpflanzen IV', '5': 'ZAG-Kräuterkunde V', '6': 'UTZ-Botanische Magie VI', '7': 'Seltene magische Gewächse VII' }, info: 'Kräuterkunde erklärt Pflege, Ernte und Gefahren magischer Pflanzen, von Alraunen bis zu bissigen Ranken. Bewertet werden praktische Topfarbeit und ein kurzer Pflanzensteckbrief.', sessions: [{ day: 'tuesday', slot: 'period2' }, { day: 'thursday', slot: 'period3', yearLevels: [3,4,5,6,7] }] },
    { id: 'history', name: 'Geschichte der Zauberei', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5], teacher: 'Professor Cuthbert Binns', room: 'Klassenzimmer 4F, vierter Stock, Haupttreppenhaus-Westseite', icon: '', iconScale: 0.9, color: '#8b7b69', examForm: 'Theoretische Prüfung am Halbjahresende und Essay zu einem historischen Konflikt.', materials: ['Zeitleisten-Pergament', 'Federkiel'], literatureByYear: { '1': 'Geschichte der Zauberei I', '2': 'Koboldaufstände II', '3': 'Magische Gesetzgebung III', '4': 'Internationale Zaubererkonflikte IV', '5': 'ZAG-Chroniken V' }, info: 'Geschichte der Zauberei behandelt Koboldaufstände, Zaubereigesetze und Wendepunkte der magischen Gesellschaft. Die Prüfung ist meist schriftlich: Daten, Ursachen, Folgen und ein kurzer Essay zu einem historischen Konflikt.', sessions: [{ day: 'monday', slot: 'period3' }, { day: 'thursday', slot: 'period2' }] },
    { id: 'potions', name: 'Zaubertränke', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Horace Slughorn', room: 'Kerker, Tränkeklassenzimmer B, Slytherin-Kerkerflügel', icon: '', iconScale: 0.88, color: '#6f5aa8', examForm: 'Praktische Brauprüfung, Laborprotokoll und Zutatenkunde-Klausur.', materials: ['Kessel aus Zinn', 'Waage', 'Glasphiolen', 'Zutatenmesser'], literatureByYear: { '1': 'Einführung in Zaubertränke', '2': 'Kessel, Kräuter und klare Schnitte II', '3': 'Potente Zaubertränke und ihre Gefahren III', '4': 'Gegenmittel und Elixiere IV', '5': 'ZAG-Zaubertränke V', '6': 'UTZ-Zaubertränke VI', '7': 'Meistertränke VII' }, info: 'Zaubertränke schult Rezepttreue, Zutatenkunde und das Erkennen feiner Farb- und Geruchsveränderungen. In der Prüfung braust du einen Trank unter Zeitdruck und erklärst danach Wirkung, Risiken und Alternativzutaten.', sessions: [{ day: 'tuesday', slot: 'period1' }, { day: 'wednesday', slot: 'period3' }, { day: 'friday', slot: 'period1', yearLevels: [3,4,5,6,7] }] },
    { id: 'transfiguration', name: 'Verwandlung', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1,2,3,4,5,6,7], teacher: 'Professor Minerva McGonagall', room: 'Verwandlungsklassenzimmer, erster Stock, Haupttreppenhaus-Ostseite', icon: '', iconScale: 0.9, color: '#030302', examForm: 'Praktische Umwandlung, mündliche Formelabfrage und Theorieprüfung.', materials: ['Übungsobjekte', 'Notizpergament'], literatureByYear: { '1': 'Leitfaden für Verwandlungsanfänger', '2': 'Form und Funktion II', '3': 'Tierverwandlung III', '4': 'Stabile Objektverwandlung IV', '5': 'ZAG-Verwandlung V', '6': 'UTZ-Verwandlung VI', '7': 'Fortgeschrittene Transfiguration VII' }, info: 'Verwandlung verlangt Konzentration, klare Vorstellungskraft und saubere Formveränderungen von Objekten oder Tieren. Prüfungen bestehen aus Theorie zu Ausnahmen und einer praktischen Umwandlung mit Genauigkeitsbewertung.', sessions: [{ day: 'monday', slot: 'period1' }, { day: 'wednesday', slot: 'period2', yearLevels: [3,4,5,6,7] }, { day: 'wednesday', slot: 'period1', yearLevels: [1,2] }] },
    { id: 'flying', name: 'Besenflugstunde', category: 'pflicht', required: true, elective: false, countsForMinimum: false, yearLevels: [1], teacher: 'Madam Rolanda Hooch', room: 'Flugplatz neben dem Quidditchfeld', icon: '', iconScale: 0.92, color: '#5f8fa1', examForm: 'Praktischer Flugparcours mit Start, Bremsung und Landung.', materials: ['Flugausrüstung wird gestellt', 'Wetterfester Umhang'], literatureByYear: { '1': 'Quidditch im Wandel der Zeiten I' }, info: 'Besenflugstunde vermittelt Aufsteigen, Schweben, Bremsen und sichere Kurven auf dem Schulbesen. Die Prüfung ist praktisch: kontrollierter Start, kurzer Parcours, Landung und korrekte Sicherheitsregeln.', sessions: [{ day: 'friday', slot: 'period4' }] },
    { id: 'ancient-runes', name: 'Alte Runen', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [3,4,5,6,7], teacher: 'Professor Bathsheda Babbling', room: 'Runenkabinett, fünfter Stock, Bibliotheksflügel', icon: '', iconScale: 0.88, color: '#caa76a', examForm: 'Übersetzungsprüfung, Runenportfolio und kurzer Vortrag.', materials: ['Runenwörterbuch', 'Übersetzungstafel'], literatureByYear: { '3': 'Alte Runen leicht gemacht III', '4': 'Runenfamilien IV', '5': 'ZAG-Runenübersetzung V', '6': 'UTZ-Runenmagie VI', '7': 'Runenarchive VII' }, info: 'Alte Runen führt in Übersetzung, Grammatik und Deutung magischer Schriftzeichen ein. Die Prüfung verlangt das Entziffern eines Runentextes, eine kurze Übersetzung und die Erklärung möglicher Schutzwirkungen.', sessions: [{ day: 'tuesday', slot: 'period4' }, { day: 'friday', slot: 'period4' }] },
    { id: 'arithmancy', name: 'Arithmantik', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [3,4,5,6,7], teacher: 'Professor Septima Vector', room: 'Arithmantikraum, siebter Stock, Ravenclaw-Turmzugang', icon: '', iconScale: 0.88, color: '#4f9aa3', examForm: 'Rechenklausur, Pergamentabgaben und Prognosevortrag.', materials: ['Zahlentafeln', 'Rechenpergament'], literatureByYear: { '3': 'Arithmantische Grundformeln III', '4': 'Zahl und Schicksal IV', '5': 'ZAG-Arithmantik V', '6': 'UTZ-Wahrscheinlichkeitsmagie VI', '7': 'Arithmantische Prognosen VII' }, info: 'Arithmantik untersucht magische Zahlenmuster, Wahrscheinlichkeiten und Charakterberechnungen. Geprüft wird mit Rechenaufgaben, Zahlenquadraten und einer begründeten Prognose aus vorgegebenen Daten.', sessions: [{ day: 'monday', slot: 'period5' }, { day: 'wednesday', slot: 'period4' }] },
    { id: 'care-creatures', name: 'Pflege magischer Geschöpfe', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [3,4,5,6,7], teacher: 'Professor Rubeus Hagrid / Professor Raue-Pritsche', room: 'Wildhüterhütte und Außengehege am Verbotenen Wald', icon: '', iconScale: 0.9, color: '#8aa95c', examForm: 'Praktische Tierpflege, Pflegeprotokoll und mündliche Artkunde.', materials: ['Drachenhauthandschuhe', 'Robuste Stiefel', 'Futterbeutel'], literatureByYear: { '3': 'Monsterbuch der Monster III', '4': 'Artenschutz magischer Geschöpfe IV', '5': 'ZAG-Geschöpfe V', '6': 'UTZ-Tierpflege VI', '7': 'Magische Wildnis VII' }, info: 'Pflege magischer Geschöpfe behandelt Fütterung, Verhalten, Gefahrenstufen und respektvollen Umgang mit magischen Tieren. Die Prüfung umfasst sichere Annäherung, Pflegeprotokoll und mündliche Fragen zur Artkunde.', sessions: [{ day: 'monday', slot: 'period4' }, { day: 'thursday', slot: 'period4' }] },
    { id: 'divination', name: 'Wahrsagen', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [3,4,5,6,7], teacher: 'Professor Sybill Trelawney / Firenze', room: 'Nordturm, Wahrsagezimmer', icon: '', iconScale: 0.86, color: '#9d6fb2', examForm: 'Deutungsvortrag, Traumtagebuch und mündliche Symbolprüfung.', materials: ['Kristallkugel nach Ansage', 'Teetasse', 'Traumtagebuch'], literatureByYear: { '3': 'Das Entnebeln der Zukunft III', '4': 'Traumzeichen und Teeblätter IV', '5': 'ZAG-Wahrsagen V', '6': 'UTZ-Deutungskunst VI', '7': 'Prophetische Methoden VII' }, info: 'Wahrsagen arbeitet mit Teeblättern, Traumdeutung, Kristallkugeln und Zeichenlehre. Die Prüfung ist eine Mischung aus Deutungsvortrag, Symbolkenntnis und einer schriftlichen Reflexion über die Methode.', sessions: [{ day: 'tuesday', slot: 'period4' }, { day: 'thursday', slot: 'period5' }] },
    { id: 'muggle-studies', name: 'Muggelkunde', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [3,4,5,6,7], teacher: 'Professor Charity Burbage', room: 'Muggelkunderaum, dritter Stock, Westflügel von Hogwarts', icon: '', iconScale: 0.88, color: '#cc7d55', examForm: 'Objektbericht, theoretische Prüfung und kurzer Vergleichsvortrag.', materials: ['Objektprotokoll', 'Bleistift', 'Nichtmagisches Beispielobjekt nach Ansage'], literatureByYear: { '3': 'Muggelkunde-Grundbuch III', '4': 'Elektrizität und andere Rätsel IV', '5': 'ZAG-Muggelkunde V', '6': 'UTZ-Magisch-Muggelige Beziehungen VI', '7': 'Muggelgesellschaft VII' }, info: 'Muggelkunde erklärt Technik, Gesellschaft und Alltagsgegenstände nichtmagischer Menschen. Die Prüfung besteht aus Begriffserklärungen, einem Objektbericht und einer kurzen Analyse magisch-muggeliger Missverständnisse.', sessions: [{ day: 'wednesday', slot: 'period4' }, { day: 'friday', slot: 'period5' }] },
    { id: 'apparition', name: 'Apparieren und Disapparieren', category: 'zusatz', required: false, elective: true, countsForMinimum: false, yearLevels: [6,7], teacher: 'Wilkie Twycross', room: 'Große Halle, Erdgeschoss', icon: '', iconScale: 0.86, color: '#5e87c9', examForm: 'Praktische Apparierprüfung mit Zielkreis und Sicherheitsbewertung.', materials: ['Genehmigungsformular', 'Bequeme Schuhe'], literatureByYear: { '6': 'Apparieren: Ziel, Wille, Ruhe VI', '7': 'Apparieren: Prüfung und Präzision VII' }, info: 'Der Apparierkurs bereitet ältere Schülerinnen und Schüler auf kontrolliertes Verschwinden und Erscheinen vor. Die Prüfung ist praktisch und bewertet Zielgenauigkeit, Entschlossenheit und das Vermeiden von Zersplintern.', sessions: [{ day: 'saturday', slot: 'period2' }] },
    { id: 'alchemy', name: 'Alchemie', category: 'wahlpflicht', required: false, elective: true, countsForMinimum: true, yearLevels: [6,7], teacher: 'Gastprofessur, sowie Professor Dumbledore', room: 'Alchemielabor, Kerkerflügel', icon: '', iconScale: 0.86, color: '#c58f42', examForm: 'Laborprotokoll, kontrollierte Transmutation und mündliche Symbolprüfung.', materials: ['Kupferkessel', 'Schutzbrille', 'Reagenzienkasten'], literatureByYear: { '6': 'Alchemistische Symbole VI', '7': 'Transmutation und Substanz VII' }, info: 'Alchemie verbindet fortgeschrittene Stoffwandlung, Symbollehre und seltene Reaktionsketten. Die Prüfung fordert ein Laborprotokoll, eine kontrollierte Transmutation und die Erklärung alchemistischer Grundsätze.', sessions: [{ day: 'thursday', slot: 'period5' }, { day: 'saturday', slot: 'period1' }] },
    { id: 'advanced-potions', name: 'Fortgeschrittene Zaubertränke', category: 'fortgeschritten', replaces: 'potions', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Horace Slughorn', room: 'Kerker, Tränkeklassenzimmer B, Slytherin-Kerkerflügel', icon: '', iconScale: 0.88, color: '#7c65c4', examForm: 'Komplexe Brauprüfung, Forschungspergament und Zutatenkolloquium.', materials: ['Silbermesser', 'Messingwaage', 'Sicherheitsbrille', 'Saubere Phiolen'], literatureByYear: { '5': 'UTZ-Zaubertränke: Slughorns Auswahl V', '6': 'Komplexe Trankketten VI', '7': 'Meistertränke VII' }, info: 'Der fortgeschrittene Kurs vertieft seltene Rezepturen, Gegenmittel und Tränke mit enger Temperaturführung. Die Prüfung verlangt präzise Laborarbeit und eine begründete Analyse der Wirkungskette.', sessions: [{ day: 'wednesday', slot: 'period5' }] },
    { id: 'advanced-charms', name: 'Fortgeschrittene Zauberkunst', category: 'fortgeschritten', replaces: 'charms', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Filius Flitwick', room: 'Klassenzimmer 2E, zweiter Stock, Ostflügel von Hogwarts', icon: '', iconScale: 0.9, color: '#e0c16a', examForm: 'Praktische Zauberserie, Partnerprüfung und Kurzvortrag.', materials: ['Zauberkatalog', 'Zauberstabpflegeset optional'], literatureByYear: { '5': 'Fortgeschrittene Standardzauber V', '6': 'Nonverbale Zauberkunst VI', '7': 'Meisterhafte Zauberführung VII' }, info: 'Fortgeschrittene Zauberkunst verbindet mehrere Zauber zu kontrollierten Abläufen und trainiert nonverbale Grundlagen. Geprüft wird eine sichere, saubere Zauberserie mit kurzer theoretischer Begründung.', sessions: [{ day: 'monday', slot: 'period4' }] },
    { id: 'advanced-transfiguration', name: 'Fortgeschrittene Verwandlung', category: 'fortgeschritten', replaces: 'transfiguration', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Minerva McGonagall', room: 'Verwandlungsklassenzimmer, erster Stock, Haupttreppenhaus-Ostseite', icon: '', iconScale: 0.9, color: '#cf9350', examForm: 'Praktische Präzisionsverwandlung, Theorieessay und mündliche Verteidigung.', materials: ['Messinstrumente', 'Übungsfiguren'], literatureByYear: { '5': 'Mittlere Verwandlung V', '6': 'Komplexe Transfiguration VI', '7': 'Grenzen der Verwandlung VII' }, info: 'Der fortgeschrittene Kurs fordert präzise, stabile Verwandlungen und die Kenntnis gesetzlicher Grenzen. Die Prüfung bewertet Genauigkeit, Stabilität und Erklärung der verwendeten Formel.', sessions: [{ day: 'tuesday', slot: 'period5' }] },
    { id: 'advanced-creatures', name: 'Fortgeschrittene Pflege magischer Geschöpfe', category: 'fortgeschritten', replaces: 'care-creatures', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Rubeus Hagrid / Professor Raue-Pritsche', room: 'Außengehege am Verbotenen Wald, Wildhüterpfad', icon: '', iconScale: 0.9, color: '#9fbd69', examForm: 'Betreutes Pflegeprojekt, Gefahrenanalyse und mündliche Prüfung.', materials: ['Schwere Drachenhauthandschuhe', 'Schutzmantel', 'Futterplanbuch', 'Tierheilkundeset'], literatureByYear: { '5': 'Gefahrenklassen und Pflegeprojekte V', '6': 'UTZ-Tierpflege VI', '7': 'Magische Wildnis VII' }, info: 'Fortgeschrittene Pflege magischer Geschöpfe arbeitet mit anspruchsvolleren Arten, Notfallroutinen und Verhaltensbeobachtung. Die Prüfung ist ein betreutes Pflegeprojekt mit Sicherheitsanalyse.', sessions: [{ day: 'friday', slot: 'period4' }] },
    { id: 'advanced-defence', name: 'Fortgeschrittene Verteidigung gegen die dunklen Künste', category: 'fortgeschritten', replaces: 'defence', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Severus Snape', room: 'Verteidigungsklassenzimmer, dritter Stock, Nordflügel von Hogwarts', icon: '', iconScale: 0.9, color: '#a83d4f', examForm: 'Praktisches Verteidigungsduell, mündliche Gefahrenanalyse und Theorieprüfung.', materials: ['Schutzumhang empfohlen', 'Duellierprotokoll'], literatureByYear: { '5': 'ZAG-Verteidigung: Fortgeschrittene Schutzzauber V', '6': 'UTZ-Verteidigung und nonverbale Abwehr VI', '7': 'Meisterkurs Defensive Magie VII' }, info: 'Der fortgeschrittene Verteidigungskurs vertieft nonverbale Abwehr, schnelle Gegenfläche und taktisches Verhalten in Gefahrensituationen. Professor Snape prüft besonders Präzision, Ruhe und saubere Analyse.', sessions: [{ day: 'thursday', slot: 'period5' }] },
    { id: 'advanced-herbology', name: 'Fortgeschrittene Kräuterkunde', category: 'fortgeschritten', replaces: 'herbology', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Pomona Sprout', room: 'Gewächshaus Vier, Schlossgärten hinter dem Hauptgebäude', icon: '', iconScale: 0.88, color: '#80BFAD', examForm: 'Betreutes Pflanzenprojekt, Sicherheitsprotokoll und mündliche Prüfung.', materials: ['Drachenhauthandschuhe', 'Komplette Schutzausrüstung', 'Gegengifte'], literatureByYear: { '5': 'ZAG-Kräuterkunde: Gefährliche Gewächse V', '6': 'UTZ-Botanische Magie VI', '7': 'Seltene magische Gewächse VII' }, info: 'Fortgeschrittene Kräuterkunde arbeitet mit empfindlichen und gefährlicheren Pflanzenarten. Die Prüfung bewertet Pflege, Sicherheitsverhalten und ein sauberes Pflanzenprotokoll.', sessions: [{ day: 'monday', slot: 'period5' }] },
    { id: 'advanced-history', name: 'Fortgeschrittene Geschichte der Zauberei', category: 'fortgeschritten', replaces: 'history', required: false, elective: true, countsForMinimum: true, yearLevels: [5,6,7], teacher: 'Professor Cuthbert Binns', room: 'Klassenzimmer 4F, vierter Stock, Haupttreppenhaus-Westseite', icon: '', iconScale: 0.9, color: '#9f8b73', examForm: 'Quellenanalyse, Essay und mündlicher Kurzvortrag.', materials: ['Quellenmappe', 'Zeitleisten-Pergament'], literatureByYear: { '5': 'ZAG-Chroniken V', '6': 'Internationale Zaubererpolitik VI', '7': 'Archiv der magischen Konflikte VII' }, info: 'Der fortgeschrittene Geschichtskurs untersucht Quellen, politische Folgen und verdrängte Details der magischen Vergangenheit. Insbesondere ist das Anschauen echter Geschichts-Erinnerungen im Klassenzimmer Denkarium. Die Prüfung verlangt Argumentation statt reines Auswendiglernen.', sessions: [{ day: 'tuesday', slot: 'period5' }] },
    { id: 'wandmaking', name: 'Zauberstab-Herstellungskunde', category: 'zusatz', required: false, elective: true, countsForMinimum: false, yearLevels: [5,6,7], teacher: 'Garrick Ollivander', room: 'Werkraum für Zauberstabkunde, fünfter Stock, Ostflügel von Hogwarts', icon: '', iconScale: 0.9, color: '#b98d55', examForm: 'Materialkunde-Protokoll, Holz- und Kernanalyse und mündlicher Vortrag.', materials: ['Holzmuster werden gestellt', 'Schutzbrille'], literatureByYear: { '5': 'Holz, Kern und Wille V', '6': 'Zauberstabresonanz VI', '7': 'Meisterfragen der Zauberstabkunde VII' }, info: 'Zauberstab-Herstellungskunde erklärt Holzarten, magische Kerne, Balance und die Bindung zwischen Zauberstab und Hexe oder Zauberer. Im Kurs wird nicht frei mit gefährlichen Kernen experimentiert, sondern analysiert, dokumentiert und unter Aufsicht montiert.', sessions: [{ day: 'saturday', slot: 'period2' }] },
    { id: 'pro-quidditch', name: 'Quidditch Profitraining', category: 'zusatz', required: false, elective: true, countsForMinimum: false, yearLevels: [5,6,7], teacher: 'Madam Rolanda Hooch', room: 'Quidditchfeld und Taktikraum', icon: '', iconScale: 0.9, color: '#bc6b46', examForm: 'Taktikanalyse, Konditionsprüfung und betreuter Flugparcours.', materials: ['Profi-Ausrüstung wird gestellt', 'Empfohlen: Sportumhang', 'Wasserflasche'], literatureByYear: { '5': 'Quidditch-Taktiken V', '6': 'Positionsspiel und Sucherdrills VI', '7': 'Profi-Training und Spielanalyse VII' }, info: 'Quidditch Profitraining richtet sich an ältere Schülerinnen und Schüler mit ernsthaftem Interesse an Mannschaftsspiel, Taktik und professioneller Spielvorbereitung. Madam Hooch prüft Übersicht, Fairness und kontrolliertes Fliegen.', sessions: [{ day: 'saturday', slot: 'evening' }] },
    { id: 'dragonology', name: 'Drachenkunde', category: 'zusatz', required: false, elective: true, countsForMinimum: false, yearLevels: [5,6,7], teacher: 'Charlie Weasley', room: 'Außengehege am Verbotenen Wald, Wildhüterpfad', icon: '', iconScale: 0.9, color: '#b85f4a', examForm: 'Gefahrenanalyse, Beobachtungsprotokoll und mündliche Artkunde.', materials: ['Feuerfester Umhang wird gestellt', 'Fernglas'], literatureByYear: { '5': 'Drachenarten Europas V', '6': 'Drachenpflege und Schutzgebiete VI', '7': 'Fortgeschrittene Drachenkunde VII' }, info: 'Drachenkunde behandelt Artenkunde, Schutzabstände, Verhalten und die Arbeit in Reservaten. Der Unterricht bleibt beobachtend und sicherheitsorientiert, auch wenn die Themen ordentlich Feuer haben.', sessions: [{ day: 'sunday', slot: 'period5' }] },
    { id: 'animagus-study', name: 'Animagus-Ergründung', category: 'zusatz', required: false, elective: true, countsForMinimum: false, yearLevels: [5,6,7], teacher: 'Professor Minerva McGonagall', room: 'Verwandlungsklassenzimmer, erster Stock, Haupttreppenhaus-Ostseite', icon: '', iconScale: 0.9, color: '#cf9350', examForm: 'Theorieprüfung, Ethik-Essay und mündliche Sicherheitsabfrage.', materials: ['Verwandlungsjournal', 'Registrierungsformular-Muster'], literatureByYear: { '5': 'Animagusrecht und Selbstbild V', '6': 'Körper, Wille und Gestalt VI', '7': 'Grenzen freiwilliger Verwandlung VII' }, info: 'Animagus-Ergründung ist kein heimlicher Selbstversuch, sondern ein streng theoretischer und sicherheitsbewusster Kurs über Voraussetzungen, Risiken, Registrierung und Geschichte der Animagi.', sessions: [{ day: 'friday', slot: 'evening' }] },
  ],
  clubs: [
    { id: 'wizard-chess', name: 'Zauberschach-Club', minYear: 1, leader: 'Ewan MacLeod', room: 'Große Halle, Erdgeschoss', day: 'saturday', slot: 'period4', color: '#b8a572', materials: ['Eigenes Schachset oder Schulset', 'Notizpergament'], info: 'Der Zauberschach-Club spielt betreute Partien, Taktikaufgaben und kleine Haus-Turniere. Ewan MacLeod achtet darauf, dass mit fairen Mitteln gespielt wird und die magischen Sonderregeln eingehalten werden.' },
    { id: 'gobstones', name: 'Koboldstein-Club', minYear: 1, leader: 'Niamh O’Connell', room: 'Innenhof, Erdgeschoss', day: 'sunday', slot: 'period3', color: '#7e9b78', materials: ['Koboldstein-Set', 'Reinigungstuch', 'Robuster Umhang'], info: 'Im Koboldstein-Club werden Zielwürfe, Turnierregeln und Hausduelle geübt. Niamh O’Connell führt eine Rangliste und duldet keine verzauberten Ersatzsteine.' },
    { id: 'quidditch', name: 'Quidditch-Training', minYear: 2, leader: 'Madam Rolanda Hooch', room: 'Quidditchfeld', color: '#bc6b46', materials: ['Mannschaftsausrüstung und Trainingsbesen werden gestellt', 'Empfohlen: Sportumhang', 'Wasserflasche'], info: 'Quidditch-Training findet pro Haus zweimal wöchentlich statt. Die Feldzeiten sind getrennt, um Doppelbelegung zu vermeiden.', houseSessions: { gryffindor: [{ day: 'tuesday', slots: ['training1','training2'] }, { day: 'saturday', slots: ['training1','training2'] }], hufflepuff: [{ day: 'monday', slots: ['training1','training2'] }, { day: 'sunday', slots: ['training1','training2'] }], ravenclaw: [{ day: 'wednesday', slots: ['training1','training2'] }, { day: 'saturday', slots: ['period1','period2'] }], slytherin: [{ day: 'thursday', slots: ['training1','training2'] }, { day: 'friday', slots: ['training1','training2'] }] } },
    { id: 'duelling', name: 'Duellierclub', minYear: 3, leader: 'Harry Potter', room: 'Große Halle, Erdgeschoss, Hauptgebäude', day: 'friday', slot: 'evening', color: '#ad4d58', materials: ['Zauberstab', 'Schutzumhang', 'Duellierprotokoll'], info: 'Der Duellierclub übt Verbeugung, Schildzauber, Entwaffnung und kontrollierte Gegenzauber. Harry Potter legt Wert auf sichere Ausführung und keine Angeberei.' },
    { id: 'art', name: 'Art Club', minYear: 1, leader: 'Maisie Campbell', room: 'Kunstraum, dritter Stock, Westflügel von Hogwarts', day: 'sunday', slot: 'period4', color: '#c28f86', materials: ['Skizzenbuch', 'Farbkasten', 'Selbstmischende Tinte'], info: 'Der Art Club gestaltet magische Skizzen, bewegte Portraitstudien, magische Fotografie und Plakate für Hausveranstaltungen. Maisie Campbell organisiert am Monatsende eine kleine Galerie im Korridor.' },
    { id: 'astronomy-club', name: 'Astronomie-Club', minYear: 2, leader: 'Seamus Byrne', room: 'Astronomieturm, oberste Plattform', day: 'saturday', slot: 'night', color: '#526eb8', materials: ['Teleskop', 'Warmer Umhang', 'Sternenjournal'], info: 'Der Astronomie-Club beobachtet Meteorströme, Planetenbahnen und seltene Konstellationen. Seamus Byrne führt ein gemeinsames Sternenjournal für alle Häuser.' },
    { id: 'homework', name: 'Hausaufgaben-Treff', minYear: 1, leader: 'Vertrauensschülerinnen und Vertrauensschüler', room: 'Bibliothek, vierter Stock', day: 'sunday', slot: 'evening', color: '#9c8b6a', materials: ['Offene Aufgaben', 'Lehrbücher', 'Federkiel'], info: 'Der Hausaufgaben-Treff bietet ruhige Arbeitszeit, Nachfragen und Literaturtipps. Hin und wieder unterstützen Lehrkräfte und geben hilfreiche Tipps.' },
    { id: 'creatures-club', name: 'Magische-Geschöpfe-Club', minYear: 3, leader: 'Hagrid', room: 'Wildhüterhütte am Verbotenen Wald', day: 'saturday', slot: 'period3', color: '#7ca05e', materials: ['Drachenhauthandschuhe', 'Robuste Stiefel', 'Futterbeutel'], info: 'Der Club besucht ungefährliche Geschöpfe, baut Futterpläne und lernt Spuren zu lesen. Teilnahme erfordert feste Schuhe und Respekt vor den Tierwesen.' },
    { id: 'charms-club', name: 'Zauberkunst-Club', minYear: 2, leader: 'Professor Flitwick', room: 'Klassenzimmer 2E, zweiter Stock, Ostflügel von Hogwarts', day: 'saturday', slot: 'period5', color: '#ceb85b', materials: ['Zauberstab', 'Übungsobjekte', 'Zauberstabpolitur'], info: 'Im Zauberkunst-Club werden Sonderzauber, Miniwettbewerbe und präzise Bewegungstechnik trainiert. Hin und wieder werden kleine Vorführungen demonstriert.' },
    { id: 'rat-racing', name: 'Rattenrennen-Club', minYear: 1, leader: 'Callum Fraser', room: 'Alter Korridor im Erdgeschoss', day: 'sunday', slot: 'period2', color: '#9c8e85', materials: ['Haustiergenehmigung', 'Mini-Hindernisse', 'Leckerli'], info: 'Der Rattenrennen-Club ist ein harmloser Wettlauf kleiner Haustiere mit Hindernissen. Callum Fraser achtet auf Pflege, Pausen und faire Rennen.' },
    { id: 'dance', name: 'Tanzclub', minYear: 2, leader: 'Professor McGonagall', room: 'Unbenutztes Klassenzimmer, erster Stock', day: 'saturday', slot: 'evening', color: '#ac789e', materials: ['Bequeme Schuhe', 'Festumhang optional'], info: 'Der Tanzclub übt Gesellschaftstänze für Bälle und festliche Abende. Bewertet wird nicht, aber Taktgefühl rettet mehr Würde als man denkt.' },
    { id: 'slug-club', name: 'Slug Club', minYear: 4, leader: 'Professor Slughorn', room: 'Professor Slughorns Büro, Kerkerflügel', day: 'sunday', slot: 'period1', color: '#9db55a', materials: ['Gepflegter Umhang', 'Gesprächsnotizen', 'Gastgeschenk optional'], info: 'Der Slug Club versammelt begabte, gut vernetzte oder besonders interessante Schülerinnen und Schüler. Professor Slughorn lädt zu Gesprächen, kleinen Empfängen und gelegentlichen Kostproben ein.' },
    { id: 'runes-club', name: 'Alte-Runen-Club', minYear: 3, leader: 'Professor Babbling', room: 'Runenkabinett, fünfter Stock', day: 'friday', slot: 'evening', color: '#bea062', materials: ['Runenwörterbuch', 'Kohlepapier', 'Übersetzungstafel'], info: 'Der Alte-Runen-Club übersetzt Inschriften, entwirft Schutzzeichen und vergleicht Runenfamilien. Ergebnisse landen im gemeinsamen Runenheft oder werden in den Vitrinen ausgestellt.' },
    { id: 'frog-choir', name: 'Froschchor', minYear: 1, leader: 'Professor Flitwick', room: 'Musikgalerie, dritter Stock, Ostflügel von Hogwarts', day: 'saturday', slot: 'period2', color: '#6f9e72', materials: ['Notenblatt', 'Stimmtee', 'Geduld mit Fröschen'], info: 'Der Froschchor probt magische Mehrstimmigkeit mit Amphibienbegleitung. Es besteht keine Pflicht bei Auftritten mitzumachen.' },
    { id: 'potions-circle', name: 'Trankzirkel', minYear: 4, leader: 'Professor Snape', room: 'Kerker, Tränkeklassenzimmer A, Slytherin-Kerkerflügel', day: 'saturday', slot: 'period3', color: '#7666a8', materials: ['Kessel', 'Schutzbrille', 'Saubere Phiolen', 'Zutatenmesser'], info: 'Der Trankzirkel vertieft Zutatenkunde, Schneidetechnik und seltene Rezeptvarianten. Professor Snape erwartet saubere Arbeitsplätze, Kreativität und genaue Protokolle.' },
    { id: 'book-club', name: 'Buchclub', minYear: 1, leader: 'Madam Pince', room: 'Bibliothek, vierter Stock, Bibliotheksflügel', day: 'sunday', slot: 'period1', color: '#947a5f', materials: ['Aktuelles Buch', 'Lesezeichen', 'Notizpergament'], info: 'Der Buchclub trifft sich zu wöchentlichen Buchbesprechungen, Empfehlungen und stillen Lesestunden. Schülerinnen und Schüler ab Schuljahrgang 5 dürfen unter Aufsicht auch in die verbotene Abteilung.' },
    { id: 'magical-cooking', name: 'Magisches Kochen', minYear: 2, leader: 'Dobby', room: 'Hogwarts-Küche, Kellergewölbe nahe den Hufflepuff-Fässern', day: 'sunday', slot: 'period4', color: '#d49f6a', materials: ['Schürze', 'Holzlöffel', 'Rezeptpergament'], info: 'Magisches Kochen zeigt einfache Zauber für sichere Küchenarbeit, schwebende Schüsseln und festliche Hausrezepte. Dobby achtet streng darauf, dass niemand hungrig geht.' },
    { id: 'first-aid', name: 'Magische erste Hilfe', minYear: 3, leader: 'Poppy Pomfrey', room: 'Krankenflügel, erster Stock, Hospitalflügel', day: 'saturday', slot: 'period4', color: '#80BFAD', materials: ['Verbandsrolle', 'Heilkundemappe', 'Saubere Handschuhe'], info: 'Magische erste Hilfe behandelt Verbände, Schockzauber, Fluchverletzungen und wann sofort Madam Pomfrey gerufen werden muss. Praktische Übungen bleiben ungefährlich.' },
    { id: 'hogsmeade-tutoring', name: 'Schülerhilfe Hogsmeade', minYear: 5, leader: 'Professor McGonagall', room: 'Drei Besen, Hogsmeade', day: 'sunday', slot: 'period3', color: '#ba875b', materials: ['Übungsaufgaben', 'Lehrbuch', 'Butterbiergeld'], info: 'Schülerhilfe Hogsmeade ist ein Club für soziales Engagement in Hogsmeade. Professor McGonagall achtet auf klare Ziele und pünktliche Rückkehr, denn es ist kein zusätzlicher Besuch im Honigtopf.' },
    { id: 'boats-fishing', name: 'Boots- und Angelclub', minYear: 2, leader: 'Finlay MacNair', room: 'Bootshaus am Schwarzen See', day: 'saturday', slot: 'period1', color: '#528da8', materials: ['Wasserfester Umhang', 'Angelrute', 'Schwimmweste'], info: 'Der Boots- und Angelclub lernt sichere Bootsknoten, Wetterregeln und geduldiges Angeln am Schwarzen See. Finlay MacNair kennt jede knarrende Planke im Bootshaus.' },
    { id: 'quidditch-org', name: 'Quidditch-Organisation', minYear: 3, leader: 'Madam Rolanda Hooch', room: 'Quidditchfeld und Geräteschuppen', day: 'sunday', slot: 'period2', color: '#c48754', materials: ['Klemmbrett', 'Spielplan', 'Pfeife optional'], info: 'Die Quidditch-Orga hilft bei Spieltagen: Matches kommentieren, als Schiedsrichterassistenz unterstützen oder neue Quidditchausrüstung beschaffen und prüfen.' },
    { id: 'prefects', name: 'Vertrauensschüler / Schulsprecher', minYear: 5, leader: '', room: '', day: 'monday', slot: 'evening', color: '#F2C580', materials: ['Abzeichen', 'Sitzungspergament', 'Federkiel'], info: 'Wöchentliches Meeting mit Vertrauensschülern und Schulsprechern, um über aktuelle Lage und Zukunft von Hogwarts zu reden.', scheduleName: 'Hogwarts Treff', scheduleLeader: 'Albus Dumbledore', scheduleRoom: 'Büro des Schulleiters, siebter Stock, Gargoyle-Korridor' },
    { id: 'event-group', name: 'Eventgruppe', minYear: 3, leader: 'Professor Flitwick', room: 'Große Halle, Erdgeschoss', day: 'saturday', slot: 'evening', color: '#d2a26e', materials: ['Planungspergament', 'Dekorationsliste', 'Zauberstab'], info: 'Die Eventgruppe organisiert Partys, Maskenbälle und andere Schulveranstaltungen (auch mit Muggeltechnik). Professor Flitwick hilft bei Zaubern, Musik und sicheren schwebenden Dekorationen.' },
    { id: 'pen-pals', name: 'Brieffreunde-Hogwarts', minYear: 1, leader: 'Aoife Gallagher', room: 'Eulenturm, Westturm', day: 'sunday', slot: 'period5', color: '#8da6c9', materials: ['Briefpapier', 'Eulenleckerlis', 'Adressliste'], info: 'Brieffreunde-Hogwarts bedeutet nicht nur Briefe schreiben und senden, sondern auch Eulenpflege. Aoife Gallagher zeigt, wie man Eulen sicher versorgt und Routen plant.' },
    { id: 'caretaker-guild', name: 'Hausmeistergilde', minYear: 4, leader: 'Argus Filch', room: 'Büro von Filch, Erdgeschoss', day: 'saturday', slot: 'period5', color: '#7f7d76', materials: ['Prüfliste', 'Handlaterne', 'Arbeitshandschuhe'], info: 'Die Hausmeistergilde macht Rundgänge durch Hogwarts, prüft Ordnung und Reparaturen und hilft bei Instandhaltung, etwa am Glockenturm. Argus Filch nimmt jedes lose Scharnier persönlich.' },
    { id: 'house-evening-gryffindor', name: 'Haustreff Gryffindor', minYear: 1, house: 'gryffindor', houseAuto: true, leader: 'Professor McGonagall', room: 'Gryffindor-Gemeinschaftsraum, Gryffindor-Turm', day: 'monday', slot: 'evening', color: '#8f1d22', materials: [], info: 'Wöchentliches Versammeln im Gemeinschaftsraum, um aktuelle Themen zu besprechen, Erfolge zu feiern und Hausangelegenheiten zu klären.' },
    { id: 'house-evening-hufflepuff', name: 'Haustreff Hufflepuff', minYear: 1, house: 'hufflepuff', houseAuto: true, leader: 'Professor Sprout', room: 'Hufflepuff-Gemeinschaftsraum, Kellerflur nahe den Küchen', day: 'tuesday', slot: 'evening', color: '#d9ad35', materials: [], info: 'Wöchentliches Versammeln im Gemeinschaftsraum, um aktuelle Themen zu besprechen, Erfolge zu feiern und Hausangelegenheiten zu klären.' },
    { id: 'house-evening-ravenclaw', name: 'Haustreff Ravenclaw', minYear: 1, house: 'ravenclaw', houseAuto: true, leader: 'Professor Flitwick', room: 'Ravenclaw-Gemeinschaftsraum, Ravenclaw-Turm', day: 'wednesday', slot: 'evening', color: '#4465A6', materials: [], info: 'Wöchentliches Versammeln im Gemeinschaftsraum, um aktuelle Themen zu besprechen, Erfolge zu feiern und Hausangelegenheiten zu klären.' },
    { id: 'house-evening-slytherin', name: 'Haustreff Slytherin', minYear: 1, house: 'slytherin', houseAuto: true, leader: 'Professor Snape', room: 'Slytherin-Gemeinschaftsraum, Kerker unter dem See', day: 'thursday', slot: 'evening', color: '#1f6b50', materials: [], info: 'Wöchentliches Versammeln im Gemeinschaftsraum, um aktuelle Themen zu besprechen, Erfolge zu feiern und Hausangelegenheiten zu klären.' },
    { id: 'archivists', name: 'Archivare und Chronisten', minYear: 3, leader: 'Eleanor Whitby', room: 'Pokalzimmer, dritter Stock, Westflügel von Hogwarts', day: 'sunday', slot: 'period4', color: '#b79b63', materials: ['Baumwollhandschuhe', 'Inventarliste', 'Poliertuch wird gestellt'], info: 'Archivare und Chronisten reinigen Vitrinen und Pokale, dokumentieren Auszeichnungen, ordnen alte Listen und helfen bei der Vorbereitung neuer Ehrungen.' },
  ],
  trips: [
    { id: 'hogsmeade-visit', name: 'Hogsmeade Besuch', minYear: 3, location: 'Hogsmeade', date: '18. Oktober', color: '#b78a64', materials: ['Einverständniserklärung', 'Wetterfester Umhang', 'Taschengeld'], info: 'Betreuter Besuch in Hogsmeade mit Rückmeldepunkt an den Drei Besen.' },
    { id: 'diagon-alley', name: 'Winkelgasse', minYear: 1, location: 'London, Winkelgasse', date: '7. September', color: '#c99c60', materials: ['Einkaufsliste', 'Galeonenbeutel'], info: 'Ein gemeinsamer Einkaufsausflug für Schulbedarf, Bücher und Ersatzfedern. Gut geeignet, um Lehrkräfte vor dem Schuljahr bereits kennenzulernen und Kaufempfehlungen zu erhalten.' },
    { id: 'ashpeak', name: 'Drachenbeobachtungs-Plateau Ashpeak', minYear: 5, location: 'Ashpeak-Hochland', date: '22. April', color: '#b85f4a', materials: ['Drachenhauthandschuhe', 'Fernglas', 'Feuerfester Umhang'], info: 'Beobachtung geschützter Drachen aus sicherer Entfernung mit Fachprotokoll und Notfall-Portschlüssel.' },
    { id: 'mournvale', name: 'Magische Gärten von Mournvale', minYear: 3, location: 'Mournvale-Gärten', date: '9. Mai', color: '#80BFAD', materials: ['Pflanzenführer', 'Handschuhe', 'Skizzenbuch'], info: 'Botanische Exkursion zu seltenen magischen Gewächsen.' },
    { id: 'aurum-kettleworks', name: 'Aurum-Kesselwerke', minYear: 4, location: 'Aurum-Kesselwerke, Birmingham', date: '14. November', color: '#d1a352', materials: ['Schutzbrille', 'Notizpergament', 'Geschlossene Schuhe'], info: 'Werksbesuch zur Herstellung geprüfter Kessel und Laborgeräte.' },
    { id: 'astra-noctis', name: 'Observatorium Astra Noctis', minYear: 4, location: 'Astra Noctis Observatorium', date: '2. Dezember', color: '#4465A6', materials: ['Sternkarte', 'Teleskopaufsatz', 'Warmer Umhang'], info: 'Nächtliche Beobachtung besonderer Sternkonstellationen mit Astronomieprotokoll.' },
    { id: 'ministry-uk', name: 'Britisches Zaubereiministerium', minYear: 5, location: 'London, Zaubereiministerium', date: '16. Januar', color: '#5379b8', materials: ['Ausweisformular', 'Festumhang', 'Fragenkatalog'], info: 'Berufsorientierter Besuch in mehreren Ministeriumsabteilungen.' },
    { id: 'macusa', name: 'Magischer Kongress der Vereinigten Staaten von Amerika', minYear: 6, location: 'MACUSA, New York', date: '3. März', color: '#5876ad', materials: ['Reisepass für magische Reisen', 'Austauschformular', 'Notizbuch'], info: 'Internationaler Austausch zu magischem Recht und Geheimhaltung.' },
    { id: 'st-mungos', name: 'St. Mungos Krankenhaus für magische Krankheiten und Verletzungen', minYear: 5, location: 'London, St. Mungos', date: '28. Februar', color: '#80BFAD', materials: ['Heilkundemappe', 'Saubere Handschuhe', 'Fragenliste'], info: 'Einblick in magische Heilkunst, Stationen und Notfallroutinen.' },
    { id: 'beauxbatons', name: 'Beauxbatons Akademie für Magie', minYear: 6, location: 'Pyrenäen, Frankreich', date: '6. April', color: '#7da6d9', materials: ['Austauschpergament', 'Festumhang', 'Französisches Wörterbuch'], info: 'Schulaustausch mit Unterrichtsbesuch.' },
    { id: 'durmstrang', name: 'Durmstrang Institut', minYear: 6, location: 'Nordeuropa', date: '20. Januar', color: '#6f778c', materials: ['Winterumhang', 'Austauschpergament'], info: 'Schulaustausch mit Unterrichtsbesuch.' },
    { id: 'ilvermorny', name: 'Ilvermorny Schule für Hexerei und Zauberei', minYear: 6, location: 'Mount Greylock, Nordamerika', date: '24. Mai', color: '#8c9fcb', materials: ['Austauschpergament', 'Ausreisepapiere'], info: 'Transatlantischer Schulaustausch mit Unterrichtsbesuch.' }
  ],
  specialDates: [
    { name: '1. Schultag und Hauseinteilungsbankett', date: '1. September', years: [1,2,3,4,5,6,7] },
    { name: 'Quidditch-Auswahlspiele', date: '12. September', years: [2,3,4,5,6,7] },
    { name: 'Wahl der Schulsprecher', date: '18. September', years: [5,6,7] },
    { name: 'Hogsmeade-Exkursion dritter Schuljahrgang', date: '18. Oktober', years: [3] },
    { name: 'Berufsberatung mit Professor McGonagall', date: '5. November', years: [5] },
    { name: 'Beginn Winterfest', date: '20. Dezember', years: [1,2,3,4,5,6,7] },
    { name: 'Weihnachtsferien', date: '21. Dezember - 5. Januar', years: [1,2,3,4,5,6,7] },
    { name: 'ZAG-Zwischenprüfung', date: '12. Dezember', years: [5] },
    { name: 'UTZ-Zwischenprüfung', date: '13. Dezember', years: [6,7] },
    { name: 'Osterferien', date: '28. März - 12. April', years: [1,2,3,4,5,6,7] },
    { name: 'Apparierprüfung', date: '21. April', years: [6] },
    { name: 'Quidditch-Finale', date: '30. Mai', years: [1,2,3,4,5,6,7] },
    { name: 'ZAG-Prüfungen', date: '8. Juni - 19. Juni', years: [5] },
    { name: 'UTZ-Prüfungen', date: '15. Juni - 26. Juni', years: [7] },
    { name: 'Hogwarts-Abschlussfest', date: '27. Juni', years: [7] },
    { name: 'Abschlusszeremonie und Hauspunktevergabe', date: '28. Juni', years: [1,2,3,4,5,6,7] },
    { name: 'Sommerferien', date: '29. Juni - 31. August', years: [1,2,3,4,5,6,7] }
  ]
};
